name: vimrc-validation
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Run Primary Test Suite 
              uses: actions/checkout@v2
            - run: |
                sudo apt-get update 
                sudo apt -y remove vim-tiny 
                sudo apt-get install vim 
            - run: |
                curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 
            - run: |
                cd ${{github.workspace}}
                cd test
                vim -Nu vimrc +'PlugInstall --sync' +qall &> /dev/null
            - run: |
                cd ${{github.workspace}}
                cd test
                cd vader
                eval "vim -Nu ../vimrc '+Vader!*'"
